version: '3.7'

services:
  db:
    image: "postgres:11"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    #ports:
    #  - 25432:5432

  web:
    container_name: phylobook
    build: .
    # command: python /phylobook/manage.py runserver 0.0.0.0:${WEB_PORT} -v 3

    command:
      - /bin/bash
      - -c
      - |
        cron
        crontab /phylobook/crontab_process_fasta
        python /phylobook/manage.py runserver 0.0.0.0:${WEB_PORT} -v 3

    volumes:
      - ${PROJECT_PATH}:${PROJECT_PATH}

    ports:
      - ${WEB_PORT}:${WEB_PORT}

    depends_on:
      - db

    env_file:
      - .env

    

volumes:
  postgres_data: