version: '3.7'

services:
  db:
    image: "postgres:11"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - config.env

  web:
    build: .
    container_name: phylobook
    volumes:
      - /Users/jfurlong/dev/FigTree-command-line/phylobook_fixed:/data
    ports:
      - 80:80
    depends_on:
      - db
    env_file:
      - config.env

volumes:
  postgres_data: