version: '3.7'

services:
  db:
    image: "postgres:11"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build: .
    container_name: phylobook
    volumes:
      - ${PROJECT_PATH}:${PROJECT_PATH}
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: