#!/bin/bash
/phylobook/manage.py collectstatic --settings=phylobook.settings.static --noinput
touch /phylobook/phylobook/wsgi.py

# Deal with logs (should be done a better way in the future)
mkdir -p /phylobook/phylobook/logs
touch /phylobook/phylobook/logs/phylobook.log
touch /phylobook/phylobook/logs/requests.log
touch /phylobook/phylobook/logs/test.log
chmod -R 777 /phylobook/phylobook/logs