# Generated by Django 3.2.18 on 2023-04-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20230403_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
