# Generated by Django 3.2.19 on 2023-06-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_tree_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='type',
            field=models.CharField(blank=True, choices=[('Amino Acids', 'Amino Acids'), ('Nucleotides', 'Nucleotides')], max_length=256, null=True),
        ),
    ]
