# Generated by Django 3.2.19 on 2023-06-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_tree_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='type',
            field=models.CharField(blank=True, choices=[('Amino Acids', 'Amino Acids'), ('Nucleotides', 'Nucleotides'), ('Unknown', 'Unknown')], max_length=256, null=True),
        ),
    ]
