# Generated by Django 3.2.20 on 2023-07-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_tree_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='tree',
            unique_together={('project', 'name')},
        ),
    ]
