# Generated by Django 3.2.20 on 2023-07-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_add_default_lineages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='lineages',
        ),
        migrations.DeleteModel(
            name='TreeLineage',
        ),
    ]
