# Generated by Django 3.2.20 on 2023-09-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20230802_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'ordering': ['name']},
        ),
    ]
