# Generated by Django 3.2.25 on 2024-05-29 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_alter_tree_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Started', 'Started'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=256)),
                ('restarts', models.IntegerField(default=0)),
                ('pid', models.IntegerField(null=True)),
                ('created_time', models.FloatField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='projects.project')),
                ('tree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='projects.tree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
