# Generated by Django 3.2.25 on 2024-05-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_process_created_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['pk']},
        ),
        migrations.RenameField(
            model_name='process',
            old_name='restarts',
            new_name='crashes',
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed'), ('Crashed', 'Crashed'), ('Failed', 'Failed')], default='Pending', max_length=256),
        ),
    ]
